blogga/urls.py
from django.urls import path

from blogga.views import PostGaCreate, PostGaUpdate, PostGaDelete, PostGaList, PostGaDetail, AnswerGaCreate, \
    AnswerGaList

app_name = 'blogga'

urlpatterns = [

    path('insertga/', PostGaCreate.as_view(), name='post-ga'),
    path('answerga/<int:pk>/', AnswerGaCreate.as_view(), name='answer-ga'),
    path('updatega/<int:pk>/', PostGaUpdate.as_view(), name='update-ga'),
    path('deletega/<int:pk>/', PostGaDelete.as_view(), name='delete-ga'),
    path('listga/', PostGaList.as_view(), name='list-ga'),
    path('listaswga/', AnswerGaList.as_view(), name='listasw-ga'),
    path('<slug:slug>/', PostGaDetail.as_view(), name='detail-ga'),

]

blogmin/urls.py
from django.urls import path

from blogmin.views import PostMinCreate, PostMinUpdate, PostMinDelete, PostMinList, PostMinDetail, AnswerMinCreate, \
    AnswerMinList

app_name = 'blogmin'

urlpatterns = [

    path('insertmin/', PostMinCreate.as_view(), name='post-min'),
    path('answermin/<int:pk>/', AnswerMinCreate.as_view(), name='answer-min'),
    path('updatemin/<int:pk>/', PostMinUpdate.as_view(), name='update-min'),
    path('deletemin/<int:pk>/', PostMinDelete.as_view(), name='delete-min'),
    path('listmin/', PostMinList.as_view(), name='list-min'),
    path('listaswmin/', AnswerMinList.as_view(), name='listasw-min'),
    path('<slug:slug>', PostMinDetail.as_view(), name='detail-min'),

]

rachaqi/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('paginas.urls', namespace='paginas')),
    path('blogga/', include('blogga.urls', namespace='blogga')),
    path('blogiot/', include('blogiot.urls', namespace='blogiot')),
    path('blogmin/', include('blogmin.urls', namespace='blogmin')),

]

handler404 = 'paginas.views.handler404'

handler500 = 'paginas.views.handler500'

blogmin/models.py
from django.contrib.auth.models import User
from django.db import models

from django.db.models import signals
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.
class PostMin(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Autor")
    title = models.CharField(max_length=255, verbose_name="Título")
    slug = models.SlugField(max_length=255, unique=True, verbose_name="Link")
    body = models.TextField(verbose_name="Texto")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Criado")
    updated = models.DateTimeField(auto_now=True, verbose_name="Editado")

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "{} ({})".format(self.author, self.title)

    def get_absolute_url(self):
        return reverse('blogmin:detail-min', kwargs={'slug': self.slug})


# # SIGNALS => Transforma o Título em Slug e salva no banco para exibir nas páginas!

def pre_save_min(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.title)


signals.pre_save.connect(pre_save_min, sender=PostMin)


class AnswerMin(models.Model):
    title = models.ForeignKey(PostMin, on_delete=models.CASCADE, related_name='answersmin', verbose_name='Dúvida')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Autor')
    body = models.TextField(verbose_name='Resposta')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return 'Resposta {} de {}'.format(self.body, self.author)

blogmin/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView

from .models import PostMin, AnswerMin


# Create your views here.
class PostMinCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account_login')
    model = PostMin
    fields = ['title', 'body']
    template_name = 'blogmin/templates/form-insert.html'
    success_url = reverse_lazy('blogmin:list-min')

    def form_valid(self, form):
        form.instance.author = self.request.user

        url = super().form_valid(form)

        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Incluir Mensagem MIN-DADOS"
        context['titulo_pg'] = "Incluir Post na Base de Dados: Mineração de Dados"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


class AnswerMinCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account_login')
    model = AnswerMin
    fields = ['title', 'body']
    template_name = 'blogmin/templates/form-insert.html'
    success_url = reverse_lazy('blogmin:listasw-min')

    def form_valid(self, form):
        form.instance.author = self.request.user

        url = super().form_valid(form)

        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Incluir Resposta Min. Dados"
        context['titulo_pg'] = "Incluir Resposta na Base de Dados: Mineração de Dados"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


# ################# UPDATE VIEWS ###################

class PostMinUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('account_login')
    model = PostMin
    fields = ['title', 'body']
    template_name = 'blogmin/templates/form-insert.html'
    success_url = reverse_lazy('blogmin:list-min')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(PostMin, pk=self.kwargs['pk'], author=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Editar Mensagem MIN-DADOS"
        context['titulo_pg'] = "Editar Post na Base de Dados: Mineração de Dados"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


# ################# DELETE VIEWS ###################

class PostMinDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('account_login')
    model = PostMin
    template_name = 'blogmin/templates/form-excluir.html'
    success_url = reverse_lazy('blogmin:list-min')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(PostMin, pk=self.kwargs['pk'], author=self.request.user)
        return self.object


# ################# LIST VIEWS ###################

class PostMinList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('account_login')
    model = PostMin
    template_name = 'blogmin/templates/list/list-min.html'
    paginate_by = 15

    def get_queryset(self):

        txt_title = self.request.GET.get('title')

        if txt_title:
            title = PostMin.objects.filter(title__icontains=txt_title)
        else:
            title = PostMin.objects.all()

        return title


class AnswerMinList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('account_login')
    model = AnswerMin
    template_name = 'blogmin/templates/list/list-answer-min.html'
    paginate_by = 15

    def get_queryset(self):

        txt_body = self.request.GET.get('body')

        if txt_body:
            body = AnswerMin.objects.filter(body__icontains=txt_body)
        else:
            body = AnswerMin.objects.all()

        return body


# ################# DETAIL VIEWS ###################

class PostMinDetail(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('account_login')
    model = PostMin
    template_name = 'blogmin/templates/detail/detail-min.html'

blogmin/templates/list/list-answer-min.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Lista Respostas MD.
{% endblock %}

<!-- LISTAGEM DE RESPOSTAS EM MINERAÇÃO DE DADOS -->

{% block content %}
     <div class="container bg-light mt-2">
         <div class="row">
            <div class="col mt-2">
            <h3>Lista de Respostas na Base de Dados - Mineração de Dados:</h3>
            <hr>

            <form action="?" method="GET">

                <label for="" class="font-weight-bold">Termo a Procurar:<input type="text" name="body" id=""
                  value="{{request.GET.body}}" class="p-1 border ml-2" autocomplete="off"
                  placeholder="Resposta Contém:"></label>

                <button type="submit" class="btn btn-success ml-2">Buscar</button>

                <a href="{% url 'blogmin:listasw-min' %}" class="lead btn btn-warning ml-3">Limpar</a>

            </form>

            <hr>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Autor</th>
                        <th>Dúvida</th>
                        <th>Resposta</th>
                    </tr>

                    {% for answermin in object_list %}
                        <tr>
                            <td>{{ answermin.author }}</td>
                            <td>{{ answermin.title }}</td>
                            <td>{{ answermin.body }}</td>
                        </tr>

                    {% empty %}
                     <tr>
                     <td colspan="3">Nenhum Resposta registrada neste tópico ou busca!</td>
                     </tr>

                    {% endfor %}

                </table>

                    <ul class="pagination justify-content-center">

                        {% if page_obj.has_previous %}

                            {% if request.GET.body %}
                            <li class="page-item"><a class="page-link" href="?page=1&title={{request.GET.body}}">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&title={{request.GET.body}}">Anterior</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                            {% endif %}

                        {% endif %}

                        <li class="page-item">
                            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                        </li>

                        {% if page_obj.has_next %}

                            {% if request.GET.body %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&title={{request.GET.body}}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&title={{request.GET.body}}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                            {% endif %}

                        {% endif %}
                    </ul>
                 </div>
            </div>
        </div>
     </div>

{% endblock %}

blogmin/templates/list/list-min.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Lista Posts MinDados.
{% endblock %}

<!-- LISTAGEM DE POSTs EM MINERAÇÃO DE DADOS -->

{% block content %}
     <div class="container bg-light mt-2">
        <div class="row">
            <div class="col mt-2">
    <h3>Lista de Posts na Base de Dados - Mineração de Dados:</h3>
    <hr>
            <form action="?" method="GET">

                <label for="" class="font-weight-bold">Termo a Procurar:<input type="text" name="title" id=""
                  value="{{request.GET.title}}" class="p-1 border ml-2" autocomplete="off"
                  placeholder="Nome ou Parte do Título"></label>

                <button type="submit" class="btn btn-success ml-2">Buscar</button>

                <a href="{% url 'blogmin:list-min' %}" class="lead btn btn-warning ml-3">Limpar</a>

            </form>
    <hr>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Autor</th>
                        <th>Título</th>
                        <th>Mensagem</th>
                        <th>Opções</th>
                    </tr>

                    {% for postmin in object_list %}
                        <tr>
                        <td>{{ postmin.author }}</td>
                        <td><a href="{{ postmin.get_absolute_url }}">{{ postmin.title }}</a></td>
                        <td>{{ postmin.body|truncatewords:10 }}</td>
                        <td>
                            <a href="{% url 'blogmin:update-min' postmin.pk %}" class="btn btn-warning btn-sm" title="Editar">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                                <a href="{% url 'blogmin:delete-min' postmin.pk %}" class="btn btn-danger btn-sm" title="Excluir">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </a>
                        </td>
                        </tr>

                    {% empty %}
                     <tr>
                     <td colspan="3">Nenhum Post registrado neste tópico!</td>
                     </tr>

                    {% endfor %}
                </table>

                    <ul class="pagination justify-content-center">

                        {% if page_obj.has_previous %}

                            {% if request.GET.title %}
                            <li class="page-item"><a class="page-link" href="?page=1&title={{request.GET.title}}">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&title={{request.GET.title}}">Anterior</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                            {% endif %}

                        {% endif %}

                        <li class="page-item">
                            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                        </li>

                        {% if page_obj.has_next %}

                            {% if request.GET.title %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&title={{request.GET.title}}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&title={{request.GET.title}}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                            {% endif %}

                        {% endif %}

                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}