blogga/urls.py
from django.urls import path

from blogga.views import PostGaCreate, PostGaUpdate, PostGaDelete, PostGaList, PostGaDetail, AnswerGaCreate, \
    AnswerGaList

app_name = 'blogga'

urlpatterns = [

    path('insertga/', PostGaCreate.as_view(), name='post-ga'),
    path('answerga/<int:pk>/', AnswerGaCreate.as_view(), name='answer-ga'),
    path('updatega/<int:pk>/', PostGaUpdate.as_view(), name='update-ga'),
    path('deletega/<int:pk>/', PostGaDelete.as_view(), name='delete-ga'),
    path('listga/', PostGaList.as_view(), name='list-ga'),
    path('listaswga/', AnswerGaList.as_view(), name='listasw-ga'),
    path('<slug:slug>/', PostGaDetail.as_view(), name='detail-ga'),

]

blogiot/urls.py
from django.urls import path

from blogiot.views import PostIotCreate, PostIotUpdate, PostIotDelete, PostIotList, PostIotDetail, AnswerIotCreate, \
    AnswerIotList

app_name = 'blogiot'

urlpatterns = [

    path('insertiot/', PostIotCreate.as_view(), name='post-iot'),
    path('answeriot/<int:pk>/', AnswerIotCreate.as_view(), name='answer-iot'),
    path('updateiot/<int:pk>/', PostIotUpdate.as_view(), name='update-iot'),
    path('deleteiot/<int:pk>/', PostIotDelete.as_view(), name='delete-iot'),
    path('listiot/', PostIotList.as_view(), name='list-iot'),
    path('listaswiot/', AnswerIotList.as_view(), name='listasw-iot'),
    path('<slug:slug>', PostIotDetail.as_view(), name='detail-iot'),

]

blogmin/urls.py
from django.urls import path

from blogmin.views import PostMinCreate, PostMinUpdate, PostMinDelete, PostMinList, PostMinDetail, AnswerMinCreate, \
    AnswerMinList

app_name = 'blogmin'

urlpatterns = [

    path('insertmin/', PostMinCreate.as_view(), name='post-min'),
    path('answermin/<int:pk>/', AnswerMinCreate.as_view(), name='answer-min'),
    path('updatemin/<int:pk>/', PostMinUpdate.as_view(), name='update-min'),
    path('deletemin/<int:pk>/', PostMinDelete.as_view(), name='delete-min'),
    path('listmin/', PostMinList.as_view(), name='list-min'),
    path('listaswmin/', AnswerMinList.as_view(), name='listasw-min'),
    path('<slug:slug>', PostMinDetail.as_view(), name='detail-min'),

]

paginas/urls.py
from django.urls import path

from .views import PaginaInicial, Ranking, Sobre

app_name = 'paginas'

urlpatterns = [

    path('', PaginaInicial.as_view(), name='inicio'),
    path('rank/', Ranking.as_view(), name='rank'),
    path('sobre/', Sobre.as_view(), name='sobre'),

]

rachaqi/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('paginas.urls', namespace='paginas')),
    path('blogga/', include('blogga.urls', namespace='blogga')),
    path('blogiot/', include('blogiot.urls', namespace='blogiot')),
    path('blogmin/', include('blogmin.urls', namespace='blogmin')),

]

handler404 = 'paginas.views.handler404'

handler500 = 'paginas.views.handler500'

paginas/models.py
from django.contrib.auth.models import User

# Create your models here.

paginas/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
# ################# PÁGINAS ###################

class PaginaInicial(TemplateView):
    template_name = 'paginas/index.html'


class Ranking(TemplateView):
    template_name = 'paginas/rank.html'


class Sobre(TemplateView):
    template_name = 'paginas/sobre.html'


def handler404(request, *args, **kwargs):
    return render(request, 'paginas/404.html')


def handler500(request, *args, **kwargs):
    return render(request, 'paginas/404.html')

paginas/templates/paginas/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS FontAwesome -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/56a7a1c2aa.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<header>

    <!-- Bloco Menu Principal com links -->

{% block menu %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container" role="navigation">
           <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'paginas:inicio' %}">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="{% url 'paginas:rank' %}">Rank</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-white" href="{% url 'paginas:sobre' %}">Sobre</a>
                    </li>
                </ul>

                 <ul class="nav nav-pills mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link active dropdown-toggle font-weight-bold" data-toggle="dropdown" href="#" role="button" aria-expanded="false">Inserir Dúvidas:</a>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" href="{% url 'blogga:post-ga' %}">Geometria e Álgebra</a>
                              <a class="dropdown-item" href="{% url 'blogiot:post-iot' %}">Protocolos IoT</a>
                              <a class="dropdown-item" href="{% url 'blogmin:post-min' %}">Mineração de Dados</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="https://ava.univesp.br">AVA Univesp</a>
                            </div>
                        </li>
                    </ul>

                 <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                    <a class="nav-link text-white" href="#" id="navbarMenuLink"
                                role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-circle" aria-hidden="true"></i>
                                <span id="username">{{ request.user }}</span>
                        <div class="dropdown-divider"></div>
                    </a>
                    </li>
                        <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'account_logout' %}">Sair</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'account_login' %}">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'account_signup' %}">Cadastro</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </nav>

    <!-- Fim do Bloco Menu Principal com links -->

{% endblock %}

</header>

<main class="container">

    <!-- Bloco Conteúdo Principal do Site -->

     {% block content %}
<br>
    <div class="container">
        <div class="jumbotron">
            <h2 class="display-4 font-weight-bold">RachaQI  <i class="fas fa-globe-americas fa-spin"></i> Para Alunos Univesp</h2>
            <p class="lead font-weight-bold">Não forneça simplesmente a resposta, ensine a pensar</p>
            <hr class="my-4">
            <p class="font-weight-bold">Plataforma de Compartilhamento de Conhecimento</p>
            <p class="font-weight-bold">Olá, bem-vindo ao RachaQI-Univesp!</p>
            <p class="font-weight-bold">Uma plataforma para compartilharmos o conhecimento adquirido na Univesp entre os alunos.</p>
            <p class="font-weight-bold">- Você tem alguma dúvida sobre como resolver uma questão ou sobre algum assunto que está sendo estudado? Poste
                aqui e a comunidade Univesp irá te ajudar!</p>
            <p class="font-weight-bold">- Você domina um tópico da disciplina que está sendo estudada? Compartilhe o seu conhecimento
                respondendo uma das perguntas e ajude os colegas a entenderem melhor o assunto.</p>
            <p class="font-weight-bold">Nossa filosofia é "Quem ensina aprende duas vezes; quem pratica o que ensina aprende três;
                quem não pergunta, não aprende nada!"</p>
            <p class="font-weight-bold">Junte-se a nós nessa jornada na busca pelo conhecimento!</p>
            <br>
            <a class="btn btn-primary btn-lg" href="{% url 'paginas:sobre' %}" role="button">Saiba Mais</a>
        </div>
    </div>
<br>
     {% endblock %}
         <hr>
<br>

 {% block posts %}

    <div class="container">

        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                    <h5 class="card-header text-primary ">Seção de Dúvidas GA-AL</h5>
                    <div class="card-body">
                        <h5 class="card-title">Dúvidas Publicadas</h5>
                        <p class="card-text">Dúvidas relacionadas às Atividades Avaliativas da
                            Disciplina Geometria Analítica e Álgebra Linear</p>
                        <a href="{% url 'blogga:list-ga' %}" class="btn btn-primary font-weight-bold">Verificar</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <h5 class="card-header text-primary ">Seção de Dúvidas PROT-IoT</h5>
                    <div class="card-body">
                        <h5 class="card-title">Dúvidas Publicadas</h5>
                        <p class="card-text">Dúvidas relacionadas às Atividades Avaliativas da
                            Disciplina Protocolos de Comunicação IoT</p>
                        <a href="{% url 'blogiot:list-iot' %}" class="btn btn-primary font-weight-bold">Verificar</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <h5 class="card-header text-primary ">Seção de Dúvidas MIN-DADOS</h5>
                    <div class="card-body">
                        <h5 class="card-title">Dúvidas Publicadas</h5>
                        <p class="card-text">Dúvidas relacionadas às Atividades Avaliativas da
                            Disciplina Mineração de Dados</p>
                        <a href="{% url 'blogmin:list-min' %}" class="btn btn-primary font-weight-bold">Verificar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

 {% endblock %}

</main>

<!-- Fim do Bloco Conteúdo Principal do Site -->

<br>
<footer class="mt-auto">

        <!-- Bloco acima do rodapé com links -->

        {% block rodape-links %}
        <div class="container-fluid bg-transparent p-3">
            <div style="background-color: #f8f9fa" class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5 class="text-primary font-weight-bold mt-2">Redes Sociais</h5>
                        <ul class="list-unstyled">
                            <li><a href="https://www.facebook.com/" class=" text-dark font-weight-bold">Facebook</a></li>
                            <li><a href="https://www.instagram.com/" class=" text-dark font-weight-bold">Instagram</a></li>
                            <li><a href="https://twitter.com/" class=" text-dark font-weight-bold">Twitter</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4">
                        <h5 class="text-primary font-weight-bold mt-2">Acesso rápido</h5>
                        <ul class="list-unstyled">
                             <li><a href="{% url 'paginas:inicio' %}" class=" text-dark font-weight-bold">Página Inicial</a></li>
                            <li><a href="https://ava.univesp.br" class=" text-dark font-weight-bold">AVA Univesp</a></li>
                            <li><a href="{% url 'account_login' %}" class=" text-dark font-weight-bold">Entrar</a></li>
                            <li><a href="{% url 'account_signup' %}" class=" text-dark font-weight-bold">Cadastro</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h5 class="text-primary font-weight-bold mt-2">Redes Sociais Univesp</h5>
                        <ul class="list-unstyled">
                            <li><a href="https://www.facebook.com/pages/UNIVESP-Universidade-Virtual-do-Estado-de-S%C3%A3o-Paulo/1506859409552887" class=" text-dark font-weight-bold">Facebook Univesp</a></li>
                            <li><a href="https://www.instagram.com/univespoficial/" class=" text-dark font-weight-bold">Instagram Univesp</a></li>
                            <li><a href="https://www.youtube.com/channel/UCBL2tfrwhEhX52Dze_aO3zA" class=" text-dark font-weight-bold">YouTube Univesp</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
            <!-- Fim do Bloco acima do Rodapé com links -->
        {% endblock %}

        <!-- Rodapé -->

        {% block rodape %}
        <div class="container-fluid bg-light text-center p-3">
            <div class="row">
                <div class="col-md-12 mx-auto text-center">
                    <img src="#" height="48" class="float-left" alt="">
                    <p>
                        <span class="lead">RachaQI Univesp - Desenvolvido por Projeto Integrador Univesp - Pq. Tecnológico S.J.C. -
                            Sala 005 - Grupo 007 / &copy;2022</span>
                    </p>

                </div>

            </div>

        </div>
       <!--  ******************************************vlibras************************************************************************** -->
        <div vw class="enabled">
            <div vw-access-button class="active"></div>
            <div vw-plugin-wrapper>
              <div class="vw-plugin-top-wrapper"></div>
            </div>
          </div>
          <script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
          <script>
            new window.VLibras.Widget('https://vlibras.gov.br/app');
          </script>
          <!--  ******************************************vlibras************************************************************************** -->
            {% endblock %}

<!-- Fim do Bloco Rodapé -->

    </footer>

{% block scripts %}

    <!-- Importação do JavaScript -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--USANDO EQUAÇÕES LATEX   **INÍCIO**
    se precisar colocar equações fica mais simples com este script-->
    <script>
        MathJax = {
          tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']]
          }
        };
        </script>
        <script id="MathJax-script" async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
        </script>
        <!--USANDO EQUAÇÕES LATEX   **FIM**-->

{% endblock %}

</body>

</html>

paginas/templates/paginas/form-excluir.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% block title %}

    Excluir Post...

{% endblock %}

{% block content %}
     <div class="row">
     <div class="col-md-6 mx-auto text-white">

<h3>Excluir Post da Base de Dados:</h3>

<p class="lead text-white">
    Confirme para Excluir Definitivamente seu Registro:
 </p>

 <hr>

 <form action="" method="POST">

     <p class="text-danger">
         Deseja Realmente Excluir o Registro: <strong>{{ object }} ?</strong>
     </p>

    {% csrf_token %}

    {{ form|crispy }}

     <hr class="mt-4">

    <button type="submit" class="btn btn-danger mt-3">Excluir!</button>

    <hr class="mt-3">

 </form>

</div>

</div>

{% endblock %}

paginas/templates/paginas/form-insert.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% block title %}

    Cadastrar Post em Geometria Analítica

{% endblock %}

{% block content %}
     <div class="row">
     <div class="col-md-6 mx-auto">

    <h3 class="text-white">Incluir Post na Base de Dados:</h3>

<p class="lead text-white">
    <strong>Preencha todos os campos solicitados:</strong>
 </p>

 <hr>

 <form action="" method="POST" class="text-danger">

    {% csrf_token %}

    {{ form|crispy }}

     <hr class="mt-4">

    <button type="submit" class="btn btn-primary mt-3">
       Cadastrar!
    </button>

    <hr class="mt-3">

 </form>

</div>

</div>

{% endblock %}

paginas/templates/paginas/form.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% load crispy_forms_filters %}

{% block titulo %}

    <title>Cadastrar</title>

{% endblock %}

{% block conteudo %}
     <div class="row">
     <div class="col-md-4 mx-auto">

<h3>{{ titulo }}</h3>

<p class="lead">
    Preencha todos os campos solicitados:
 </p>

<h5>{{ instrucoes }}</h5>
 <hr>

 <form action="" method="POST">

    {% csrf_token %}

    {{ form|crispy }}

     <hr class="mt-4">

    <button type="submit" class="btn btn-primary mt-3">
        {% autoescape off %}
        {{ icone }}
        {% endautoescape %}
        {{ botao }}

    </button>

    <hr class="mt-3">

 </form>

</div>

</div>

{% endblock %}

paginas/templates/paginas/index.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Racha QI Univesp.
{% endblock %}

paginas/templates/paginas/rank.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Rank de Postagens.
{% endblock %}

{% block content %}
    <br>
    <div class="container">
        <div class="jumbotron">
            <h2 class="display-4 font-weight-bold">RachaQI  <i class="fas fa-globe-americas fa-spin"></i> Para Alunos Univesp</h2>
            <p class="lead font-weight-bold">Não forneça simplesmente a resposta, ensine a pensar</p>
            <hr class="my-4">
            <p class="font-weight-bold">Plataforma de Compartilhamento de Conhecimento</p>
            <p class="font-weight-bold">Aqui listamos os usuários com mais compartilhamentos de respostas.</p>
        </div>
    </div>

{% endblock %}

paginas/templates/paginas/sobre.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Sobre o Racha QI Univesp.
{% endblock %}

  {% block content %}
<br>
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4 font-weight-bold">RachaQI  <i class="fas fa-globe-americas fa-spin"></i></h1>
            <p class="lead font-weight-bold">Não forneça simplesmente a resposta, ensine a pensar!</p>
            <hr class="my-4">
            <h3 class=" lead font-weight-bold">Plataforma de Compartilhamento de Conhecimento</h3>
            <article>
                O sistema RachaQI foi criado para que os Alunos participantes possam colocar suas dúvidas e receber ajuda
                dos colegas para a resolução de problemas relacionados às disciplinas cursadas no bimestre corrente.
            </article>
            <br>
            <a class="btn btn-primary btn-lg" href="{% url 'paginas:inicio' %}" role="button">Início</a>
        </div>
    </div>
<br>
     {% endblock %}