blogga/urls.py
from django.urls import path

from blogga.views import PostGaCreate, PostGaUpdate, PostGaDelete, PostGaList, PostGaDetail, AnswerGaCreate, \
    AnswerGaList

app_name = 'blogga'

urlpatterns = [

    path('insertga/', PostGaCreate.as_view(), name='post-ga'),
    path('answerga/<int:pk>/', AnswerGaCreate.as_view(), name='answer-ga'),
    path('updatega/<int:pk>/', PostGaUpdate.as_view(), name='update-ga'),
    path('deletega/<int:pk>/', PostGaDelete.as_view(), name='delete-ga'),
    path('listga/', PostGaList.as_view(), name='list-ga'),
    path('listaswga/', AnswerGaList.as_view(), name='listasw-ga'),
    path('<slug:slug>/', PostGaDetail.as_view(), name='detail-ga'),

]

rachaqi/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('paginas.urls', namespace='paginas')),
    path('blogga/', include('blogga.urls', namespace='blogga')),
    path('blogiot/', include('blogiot.urls', namespace='blogiot')),
    path('blogmin/', include('blogmin.urls', namespace='blogmin')),

]

handler404 = 'paginas.views.handler404'

handler500 = 'paginas.views.handler500'

blogga/models.py
from django.contrib.auth.models import User
from django.db import models

from django.db.models import signals
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.

class PostGa(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Autor")
    title = models.CharField(max_length=255, verbose_name="Título")
    slug = models.SlugField(max_length=255, unique=True, verbose_name="Link")
    body = models.TextField(verbose_name="Texto")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Criado")
    updated = models.DateTimeField(auto_now=True, verbose_name="Editado")

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "{} ({})".format(self.author, self.title)

    def get_absolute_url(self):
        return reverse('blogga:detail-ga', kwargs={'slug': self.slug})


# SIGNALS => Transforma o Título em Slug e salva no banco para exibir nas páginas!

def pre_save_ga(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.title)


signals.pre_save.connect(pre_save_ga, sender=PostGa)


class AnswerGa(models.Model):
    title = models.ForeignKey(PostGa, on_delete=models.CASCADE, related_name='answersga', verbose_name='Dúvida')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Autor')
    body = models.TextField(verbose_name='Resposta')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return 'Resposta {} de {}'.format(self.body, self.author)

blogga/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView

from .models import PostGa, AnswerGa


# Create your views here.
# ################# CREATE VIEWS ###################

class PostGaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account_login')
    model = PostGa
    fields = ['title', 'body']
    template_name = 'blogga/templates/form-insert.html'
    success_url = reverse_lazy('blogga:list-ga')

    def form_valid(self, form):
        form.instance.author = self.request.user

        url = super().form_valid(form)

        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Incluir Mensagem GA-AL"
        context['titulo_pg'] = "Incluir Post na Base de Dados: Geometria Analítica e Álgebra Linear"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


class AnswerGaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account_login')
    model = AnswerGa
    fields = ['title', 'body']
    template_name = 'blogga/templates/form-insert.html'
    success_url = reverse_lazy('blogga:listasw-ga')

    def form_valid(self, form):
        form.instance.author = self.request.user

        url = super().form_valid(form)

        return url

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Incluir Resposta GA-AL"
        context['titulo_pg'] = "Incluir Resposta na Base de Dados: Geometria Analítica e Álgebra Linear"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


# ################# UPDATE VIEWS ###################

class PostGaUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('account_login')
    model = PostGa
    fields = ['title', 'body']
    template_name = 'blogga/templates/form-insert.html'
    success_url = reverse_lazy('blogga:list-ga')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(PostGa, pk=self.kwargs['pk'], author=self.request.user)
        return self.object

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Editar Mensagem GA-AL"
        context['titulo_pg'] = "Editar Post na Base de Dados: Geometria Analítica e Álgebra Linear"
        context['botao'] = "Salvar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context


# ################# DELETE VIEWS ###################

class PostGaDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('account_login')
    model = PostGa
    template_name = 'blogga/templates/form-excluir.html'
    success_url = reverse_lazy('blogga:list-ga')

    def get_object(self, queryset=None):
        self.object = get_object_or_404(PostGa, pk=self.kwargs['pk'], author=self.request.user)
        return self.object


# ################# LIST VIEWS ###################

class PostGaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('account_login')
    model = PostGa
    template_name = 'blogga/templates/list/list-ga.html'
    paginate_by = 15

    def get_queryset(self):

        txt_title = self.request.GET.get('title')

        if txt_title:
            title = PostGa.objects.filter(title__icontains=txt_title)
        else:
            title = PostGa.objects.all()

        return title


class AnswerGaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('account_login')
    model = AnswerGa
    template_name = 'blogga/templates/list/list-answer-ga.html'
    paginate_by = 15

    def get_queryset(self):

        txt_body = self.request.GET.get('body')

        if txt_body:
            body = AnswerGa.objects.filter(body__icontains=txt_body)
        else:
            body = AnswerGa.objects.all()

        return body


# ################# Detail VIEWS ###################

class PostGaDetail(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('account_login')
    model = PostGa
    template_name = 'blogga/templates/detail/detail-ga.html'

blogga/templates/list/list-answer-ga.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Lista Respostas GA.
{% endblock %}

<!-- LISTAGEM DE RESPOSTAS EM GEOMETRIA ANALÍTICA E ÁLGEBRA LINEAR -->

{% block content %}
     <div class="container bg-light mt-2">
         <div class="row">
            <div class="col mt-2">
            <h3>Lista de Respostas na Base de Dados - Geometria Analítica e Álgebra Linear:</h3>
            <hr>

            <form action="?" method="GET">

                <label for="" class="font-weight-bold">Termo a Procurar:<input type="text" name="body" id=""
                  value="{{request.GET.body}}" class="p-1 border ml-2" autocomplete="off"
                  placeholder="Resposta Contém:"></label>

                <button type="submit" class="btn btn-success ml-2">Buscar</button>

                <a href="{% url 'blogga:listasw-ga' %}" class="lead btn btn-warning ml-3">Limpar</a>

            </form>

            <hr>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Autor</th>
                        <th>Dúvida</th>
                        <th>Resposta</th>
                    </tr>

                    {% for answerga in object_list %}
                        <tr>
                            <td>{{ answerga.author }}</td>
                            <td>{{ answerga.title }}</td>
                            <td>{{ answerga.body }}</td>
                        </tr>

                    {% empty %}
                     <tr>
                     <td colspan="3">Nenhum Resposta registrada neste tópico ou busca!</td>
                     </tr>

                    {% endfor %}

                </table>

                    <ul class="pagination justify-content-center">

                        {% if page_obj.has_previous %}

                            {% if request.GET.body %}
                            <li class="page-item"><a class="page-link" href="?page=1&title={{request.GET.body}}">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&title={{request.GET.body}}">Anterior</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                            {% endif %}

                        {% endif %}

                        <li class="page-item">
                            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                        </li>

                        {% if page_obj.has_next %}

                            {% if request.GET.body %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&title={{request.GET.body}}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&title={{request.GET.body}}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                            {% endif %}

                        {% endif %}
                    </ul>
                 </div>
            </div>
        </div>
     </div>

{% endblock %}

blogga/templates/list/list-ga.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block title %}
Lista Posts GA.
{% endblock %}

<!-- LISTAGEM DE POSTs EM GEOMETRIA ANALÍTICA E ÁLGEBRA LINEAR -->

{% block content %}
     <div class="container bg-light mt-2">
         <div class="row">
            <div class="col mt-2">
            <h3>Lista de Posts na Base de Dados - Geometria Analítica e Álgebra Linear:</h3>
            <hr>

            <form action="?" method="GET">

                <label for="" class="font-weight-bold">Termo a Procurar:<input type="text" name="title" id=""
                  value="{{request.GET.title}}" class="p-1 border ml-2" autocomplete="off"
                  placeholder="Nome ou Parte do Título"></label>

                <button type="submit" class="btn btn-success ml-2">Buscar</button>

                <a href="{% url 'blogga:list-ga' %}" class="lead btn btn-warning ml-3">Limpar</a>

            </form>

            <hr>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>Autor</th>
                        <th>Título</th>
                        <th>Mensagem</th>
                        <th>Opções</th>
                    </tr>

                    {% for postga in object_list %}
                        <tr>
                            <td>{{ postga.author }}</td>
                            <td><a href="{{ postga.get_absolute_url }}">{{ postga.title }}</a></td>
                            <td>{{ postga.body|truncatewords:10 }}</td>
                            <td>
                                <a href="{% url 'blogga:update-ga' postga.pk %}" class="btn btn-warning btn-sm" title="Editar">
                                <i class="fa fa-pencil mr-1" aria-hidden="true"></i>
                                </a>
                                <a href="{% url 'blogga:delete-ga' postga.pk %}" class="btn btn-danger btn-sm" title="Excluir">
                                    <i class="fa fa-trash ml-1" aria-hidden="true"></i>
                                </a>
                            </td>
                        </tr>

                    {% empty %}
                     <tr>
                     <td colspan="3">Nenhum Post registrado neste tópico ou busca!</td>
                     </tr>

                    {% endfor %}

                </table>

                    <ul class="pagination justify-content-center">

                        {% if page_obj.has_previous %}

                            {% if request.GET.title %}
                            <li class="page-item"><a class="page-link" href="?page=1&title={{request.GET.title}}">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&title={{request.GET.title}}">Anterior</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page=1">&laquo; Primeira</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                            {% endif %}

                        {% endif %}

                        <li class="page-item">
                            <span class="page-link">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                        </li>

                        {% if page_obj.has_next %}

                            {% if request.GET.title %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&title={{request.GET.title}}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&title={{request.GET.title}}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a></li><li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a></li>
                            {% endif %}

                        {% endif %}

                    </ul>

                 </div>
            </div>
        </div>
     </div>

{% endblock %}